### ISSUE TITLE
Self links should not rely on url

### ISSUE THREAD

**Issue by digitalsadhu** [digitalsadhu/loopback-component-jsonapi#11]
self link should be built out of url components and model components

**Comment by tsteuwer** [comment]
Why would you say that? The specification say:

"self: the link that generated the current response document."

**Comment by digitalsadhu** [comment]
Its more to do with the testing environment. Its currently correct in my implementation but when i run the tests grabbing the value from the url directly is breaking and id like to verify in the tests that self link is being generated correctly

**Comment by digitalsadhu** [comment]
not a biggie, just created the issue to remind myself to clean it up a bit at a later stage when the main features are implemented and i can afford to spend time improving the little details :)

**Comment by tsteuwer** [comment]
Gotcha! I'd love to help but haven't had the time to mess with loopback yet. I was actually just looking over api frameworks that support the json api and loved loopback

**Comment by digitalsadhu** [comment]
Yea, loopback is pretty great. I found the learning curve pretty low overall and the productivity very high.

If you ever do feel like lending a hand at all, let me know and I'd be happy to try to give you an overview and point you at some issues.

**Comment by tsteuwer** [comment]
That would be wonderful. How would you like to do it?

**Comment by digitalsadhu** [comment]
Maybe we should start by setting up a gitter room associated with the project so its a bit easier to discuss things

**Comment by digitalsadhu** [comment]
@tsteuwer I've created a gitter chatroom for the project and added you.

**Comment by digitalsadhu** [comment]
Unsure if this issue is still valid. Need to check.

**Comment by digitalsadhu** [comment]
I'm going to close this for now. I think it should be fine as is for now and we have bigger fish to fry
