### ISSUE TITLE
Individual error codes should not be generalised.

### ISSUE THREAD

**Issue by Resonance1584** [digitalsadhu/loopback-component-jsonapi#112]
When a single error occurs (such as 404) the response code should not be generalised to 400.

When multiple errors occur the response code should be generalised.

See http://jsonapi.org/format/#errors

**Comment by digitalsadhu** [comment]
Yup, good point. Should be an easy change.

**Comment by nandorstanko** [comment]
@digitalsadhu Could you take a look on this bug, please? It is very important to handle 4xx status codes individually in Ember apps (401, 422 etc.). I would just drop that case '4' part, loopback returns the codes as it should, I think. Thanks for your time and this great component, great job!

**Comment by digitalsadhu** [comment]
Hey, thanks for your interest. I'm struggling a bit with time right now but would certainly like to get this fixed. 

If you have any time and interest yourself I'd be happy to point you in the right direction. 

Otherwise I'll try to get to it as soon as I can.

**Comment by nandorstanko** [comment]
I would be happy to work on this, but as I wrote my only idea at this moment is to remove that part for 4xx errors from the generalizeStatusCode function. The jsonapi recommendation is that if the server encounters multiple errors, it should return 400, but how do we now if there are multiple error types or just one, like 422. Maybe from the response object, we could parse the item statuses from the errors node...

Anyway, if you have some other idea I can work on that, and we will see the results.

**Comment by digitalsadhu** [comment]
Hey again,
Sorry it took me so long to respond.

So first up it should be an easy change to remove the generalization to 400 here: https://github.com/digitalsadhu/loopback-component-jsonapi/blob/master/lib/errors.js#L88

Ideally we should try to generalize to 400/500 only if A. the array of errors has length greater than 1 and B. the errors are not all of the same type. I'm not actually sure if that would happen. It's possible simply removing the generalisation would be enough though it should't be too hard to add a generalisation based on A. and B.
