### ISSUE TITLE
This project dead?

### ISSUE THREAD

**Issue by speed1speed1** [digitalsadhu/loopback-component-jsonapi#118]
I see the "Not yet supported" part.
So is this project still working?

**Comment by digitalsadhu** [comment]
No way!
We are using it in production on about 4 large projects now.

**Comment by speed1speed1** [comment]
Great!
We will using this in our projects.
So do you have a deadline for "Not yet supported" part?
Thanks.

**Comment by digitalsadhu** [comment]
No, in generally most of what you need is there if you use ember js. There
are some unsupported features that ember data doesn't seem to actually use
so not a high priority for us.

There are a couple higher priority pieces that i'd like to get in as well
as some bug fixes but I don't have a specific schedule.
Hope that helps.
