### ISSUE TITLE
Why do you remove the foreign keys from the attributes

### ISSUE THREAD

**Issue by devotox** [digitalsadhu/loopback-component-jsonapi#124]
https://github.com/digitalsadhu/loopback-component-jsonapi/blob/8718a08744433a0ecba0e471ecf4a4f98564d84a/lib/serializer.js#L106

Is this part of the JSON API spec?

It seems that if your model wants that to be returned it should honor that request

**Comment by digitalsadhu** [comment]
The idea with jsonapi is that foreign keys are an implementation detail that shouldn't leak out of the server. You should be able to make your linkages any way you like and jsonapi supports this in the way its structured. 

Having said that, we have run into the occasional issue where we really need access to the foreign keys on the client side so i'm starting to think maybe we make it configurable so you can turn this feature on and off.

**Comment by devotox** [comment]
Yes being configurable I think would be the best way forward but also the fact I did not have them made me look for a better way of doing the linkages using Ember Data. So I can see why it is good not to have them as it does give a better level of abstraction but it was also a shock to me as I was wondering if I had done something wrong in loopback itself and took a while for me to realize it was actually the component stripping it out which made me further think if that was how the JSON API specced it out

**Comment by digitalsadhu** [comment]
I've implemented a feature to allow configuration that should solve this issue. See documentation here:

https://github.com/digitalsadhu/loopback-component-jsonapi/blob/1db5b9efa10ecbbb710352335ebfcdda3cd4bb7b/README.md#foreignkeys
