### ISSUE TITLE
You need a way of allowing the stack to be shown in error

### ISSUE THREAD

**Issue by devotox** [digitalsadhu/loopback-component-jsonapi#125]
I have to disable the json api component everytime i have an error that is vague so i can see the stack attribute that loopback returns and trace the error from there

**Comment by digitalsadhu** [comment]
Yea I feel your pain. The dreaded generic "type" error message is not
helpful.
I haven't had a lot of time to work on the component lately but this should
probably be high on my list. If you have anytime or interest in helping out
at all, do let me know and I can point you in the right direction.

Thanks for reporting!

**Comment by devotox** [comment]
Ok yes i can look into making some changes and sending you some pull requests.

  

Is there any way of using the component after forking without needing to
create a test server environment. i.e. do you have any scaffolding you use to
test your changes already in place?

  

Best regards,

Devonte Emokpae

  

Software Engineer

Doctify Ltd.

  

Mobile: 07447 903 346

Email: [devonte@doctify.co.uk](mailto:devonte.emokpae@doctify.co.uk)

  

Website:
[www.doctify.co.uk](http://www.doctify.co.uk/&r=cmVwbHkrMDAxZjgxY2U1ZDQ0ODFiOWE0ZWY5Y2FiZTRkZmU4OTU0MDY0M2Q1OGNjYzY5ZDU4OTJjZjAwMDAwMDAxMTM4MmJmZWE5MmExNjljZTA5YTQ2NTdiQHJlcGx5LmdpdGh1Yi5jb20=)

Company Email: [hello@doctify.co.uk](mailto:hello@doctify.co.uk)

  

![](https://link.nylas.com/open/3rtysyxy5lugisvg55odx9dgo/local-d0f7fded-
6fe9?r=cmVwbHkrMDAxZjgxY2U1ZDQ0ODFiOWE0ZWY5Y2FiZTRkZmU4OTU0MDY0M2Q1OGNjYzY5ZDU4OTJjZjAwMDAwMDAxMTM4MmJmZWE5MmExNjljZTA5YTQ2NTdiQHJlcGx5LmdpdGh1Yi5jb20=)

On Jun 22 2016, at 10:06 pm, Richard Walker &lt;notifications@github.com&gt;
wrote:  

> Yea I feel your pain. The dreaded generic "type" error message is not  
>  helpful.  
>  I haven't had a lot of time to work on the component lately but this should  
>  probably be high on my list. If you have anytime or interest in helping out  
>  at all, do let me know and I can point you in the right direction.  
>  
>  Thanks for reporting!  
>  
>  On Wed, 22 Jun 2016 at 21:43, Devonte &lt;notifications@github.com&gt;
wrote:  
>  
>  &gt; I have to disable the json api component everytime i have an error
that is  
>  &gt; vague so i can see the stack attribute that loopback returns and trace
the  
>  &gt; error from there  
>  &gt;  
>  &gt; —  
>  &gt; You are receiving this because you are subscribed to this thread.  
>  &gt; Reply to this email directly, view it on GitHub  
>  &gt; &lt;https://github.com/digitalsadhu/loopback-component-
jsonapi/issues/125&gt;,  
>  &gt; or mute the thread  
>  &gt;
&lt;https://github.com/notifications/unsubscribe/ABH2CniY6sF1CtJFDOPEoXU2b9nUCgPyks5qOZBvgaJpZM4I8Jdo&gt;  
>  &gt; .  
>  &gt;  
>

>

> —  
> You are receiving this because you authored the thread.  
> Reply to this email directly, [view it on
GitHub](https://github.com/digitalsadhu/loopback-component-
jsonapi/issues/125#issuecomment-227876868&r=cmVwbHkrMDAxZjgxY2U1ZDQ0ODFiOWE0ZWY5Y2FiZTRkZmU4OTU0MDY0M2Q1OGNjYzY5ZDU4OTJjZjAwMDAwMDAxMTM4MmJmZWE5MmExNjljZTA5YTQ2NTdiQHJlcGx5LmdpdGh1Yi5jb20=),
or [mute the thread](https://github.com/notifications/unsubscribe/AB-
BzltD6BvuPmt3Ktu_sVzMJB1CGJ-
9ks5qOaPqgaJpZM4I8Jdo&r=cmVwbHkrMDAxZjgxY2U1ZDQ0ODFiOWE0ZWY5Y2FiZTRkZmU4OTU0MDY0M2Q1OGNjYzY5ZDU4OTJjZjAwMDAwMDAxMTM4MmJmZWE5MmExNjljZTA5YTQ2NTdiQHJlcGx5LmdpdGh1Yi5jb20=).![](https://github.com/notifications/beacon
/AB-BzqrLAYpvFY3T8Fh_Wqj3KhHQfZFuks5qOaPqgaJpZM4I8Jdo.gif)

**Comment by tsteuwer** [comment]
@devotox you should be a le to do it through the unit tests or look at the emberloop project in the readme.

**Comment by devotox** [comment]
Thank you. Will start looking at getting some updates out and if you have
anything that you think is a priority I can look at those as well  
  

Best regards,

Devonte Emokpae

  

Software Engineer

Doctify Ltd.

  

Mobile: 07447 903 346

Email: [devonte@doctify.co.uk](mailto:devonte.emokpae@doctify.co.uk)

  

Website:
[www.doctify.co.uk](http://www.doctify.co.uk/&r=cmVwbHkrMDAxZjgxY2VkMWZkNTZiZDI0NTEzZWU4YmE4ZmQ2NWVjYmNiZTFiYWI1YjQ3NTBhOTJjZjAwMDAwMDAxMTM4MmM2YmY5MmExNjljZTA5YTQ2NTdiQHJlcGx5LmdpdGh1Yi5jb20=)

Company Email: [hello@doctify.co.uk](mailto:hello@doctify.co.uk)

  
![](https://link.nylas.com/open/3rtysyxy5lugisvg55odx9dgo/local-
c1c4f424-78ff?r=cmVwbHkrMDAxZjgxY2VkMWZkNTZiZDI0NTEzZWU4YmE4ZmQ2NWVjYmNiZTFiYWI1YjQ3NTBhOTJjZjAwMDAwMDAxMTM4MmM2YmY5MmExNjljZTA5YTQ2NTdiQHJlcGx5LmdpdGh1Yi5jb20=)

On Jun 22 2016, at 10:36 pm, Troy &lt;notifications@github.com&gt; wrote:  

>
[@devotox](https://github.com/devotox&r=cmVwbHkrMDAxZjgxY2VkMWZkNTZiZDI0NTEzZWU4YmE4ZmQ2NWVjYmNiZTFiYWI1YjQ3NTBhOTJjZjAwMDAwMDAxMTM4MmM2YmY5MmExNjljZTA5YTQ2NTdiQHJlcGx5LmdpdGh1Yi5jb20=)
you should be a le to do it through the unit tests or look at the emberloop
project in the readme.

>

> —  
> You are receiving this because you were mentioned.  
> Reply to this email directly, [view it on
GitHub](https://github.com/digitalsadhu/loopback-component-
jsonapi/issues/125#issuecomment-227884320&r=cmVwbHkrMDAxZjgxY2VkMWZkNTZiZDI0NTEzZWU4YmE4ZmQ2NWVjYmNiZTFiYWI1YjQ3NTBhOTJjZjAwMDAwMDAxMTM4MmM2YmY5MmExNjljZTA5YTQ2NTdiQHJlcGx5LmdpdGh1Yi5jb20=),
or [mute the thread](https://github.com/notifications/unsubscribe/AB-
Bzt13fMuJWgmc2cfpuxCzquEIZTaZks5qOaq_gaJpZM4I8Jdo&r=cmVwbHkrMDAxZjgxY2VkMWZkNTZiZDI0NTEzZWU4YmE4ZmQ2NWVjYmNiZTFiYWI1YjQ3NTBhOTJjZjAwMDAwMDAxMTM4MmM2YmY5MmExNjljZTA5YTQ2NTdiQHJlcGx5LmdpdGh1Yi5jb20=).![](https://github.com/notifications/beacon
/AB-BzlIcaRLYhQI-a9i199g9_RSUrw95ks5qOaq_gaJpZM4I8Jdo.gif)

**Comment by digitalsadhu** [comment]
Just a note, I've done a bunch of work all over the codebase today. Make sure you start working from the latest master.

**Comment by digitalsadhu** [comment]
Also, 
When setting up for local testing sometimes I like to use `npm link`

You can pull down `loopback-component-jsonapi`, run `npm install` and then `npm link`
Then is some loopback project run `npm link loopback-component-jsonapi` and the project will get symlinked into your loopback projects node_modules folder. Then you can work on the code base and test in your loopback project.

**Comment by devotox** [comment]
Thank you for the pointers and yes just updated upstream  
  

Best regards,

Devonte Emokpae

  

Software Engineer

Doctify Ltd.

  

Mobile: 07447 903 346

Email: [devonte@doctify.co.uk](mailto:devonte.emokpae@doctify.co.uk)

  

Website:
[www.doctify.co.uk](http://www.doctify.co.uk/&r=cmVwbHkrMDAxZjgxY2U4YWY5YjY2NDQ0MzJkZWY1YTk2ZTg0OTQzZWI3OTVhM2E3NjVlNGNhOTJjZjAwMDAwMDAxMTM4M2I0MWI5MmExNjljZTA5YTQ2NTdiQHJlcGx5LmdpdGh1Yi5jb20=)

Company Email: [hello@doctify.co.uk](mailto:hello@doctify.co.uk)

  
![](https://link.nylas.com/open/3rtysyxy5lugisvg55odx9dgo/local-1de2428a-
cdca?r=cmVwbHkrMDAxZjgxY2U4YWY5YjY2NDQ0MzJkZWY1YTk2ZTg0OTQzZWI3OTVhM2E3NjVlNGNhOTJjZjAwMDAwMDAxMTM4M2I0MWI5MmExNjljZTA5YTQ2NTdiQHJlcGx5LmdpdGh1Yi5jb20=)

On Jun 23 2016, at 3:28 pm, Richard Walker &lt;notifications@github.com&gt;
wrote:  

> Also,  
>  When setting up for local testing sometimes I like to use npm link

>

> You can pull down loopback-component-jsonapi, run npm install and then npm
link  
>  Then is some loopback project run npm link loopback-component-jsonapi and
the project will get symlinked into your loopback projects node_modules
folder. Then you can work on the code base and test in your loopback project.

>

> —  
> You are receiving this because you were mentioned.  
> Reply to this email directly, [view it on
GitHub](https://github.com/digitalsadhu/loopback-component-
jsonapi/issues/125#issuecomment-228067667&r=cmVwbHkrMDAxZjgxY2U4YWY5YjY2NDQ0MzJkZWY1YTk2ZTg0OTQzZWI3OTVhM2E3NjVlNGNhOTJjZjAwMDAwMDAxMTM4M2I0MWI5MmExNjljZTA5YTQ2NTdiQHJlcGx5LmdpdGh1Yi5jb20=),
or [mute the thread](https://github.com/notifications/unsubscribe/AB-
Bzq_cwl0tQT4Kw4avy5J-
H6NZ309Cks5qOpgbgaJpZM4I8Jdo&r=cmVwbHkrMDAxZjgxY2U4YWY5YjY2NDQ0MzJkZWY1YTk2ZTg0OTQzZWI3OTVhM2E3NjVlNGNhOTJjZjAwMDAwMDAxMTM4M2I0MWI5MmExNjljZTA5YTQ2NTdiQHJlcGx5LmdpdGh1Yi5jb20=).![](https://github.com/notifications/beacon
/AB-Bzmt5HVrRPQiyopJ2-NbRC1XafvoDks5qOpgbgaJpZM4I8Jdo.gif)

**Comment by Tronix117** [comment]
Solved in #246
