### ISSUE TITLE
Can't load the included data if use filter.

### ISSUE THREAD

**Issue by leeduc** [digitalsadhu/loopback-component-jsonapi#137]
I'm define customeMethod, I apply it in config, response ok. But when I used filter, It can't response the included data ?

And I hope you fix it and issue #111 . I need it.

Thanks.

**Comment by digitalsadhu** [comment]
Hey @leeduc I would advise you to use the loopback-jsonapi-model-serializer module for serialization in a remote method. I will definitely fix #111 but for an immediate solution just use https://github.com/digitalsadhu/loopback-jsonapi-model-serializer

```js
Post.myRemoteMethod = (ctx, cb) => {
  const serializer = require('loopback-jsonapi-model-serializer')
  Post.find({include: 'comments'}).then(posts => {
    cb(null, serializer(posts, Post))
  })
  .catch(cb)
}
```

**Comment by leeduc** [comment]
Thanks @digitalsadhu, I think it is a temporary solution and not follow jsonapi.org. Hope you release best solution for this issue.

Regards.

**Comment by thanh-taro** [comment]
I found a workaround. Just create a js file in `boot`:

```js
module.exports = (server) => {
  const remotes = server.remotes();

  remotes.before('**', (context, next) => {
    let query = context.req.query;
    if (query && query.include) {
      if (query.filter) {
        query.filter.include = query.include.split(',');
      } else {
        query.filter = {
          include: query.include.split(',')
        };
      }
      delete query.include;
    }
    return next();
  });
}
```

**Comment by thanh-taro** [comment]
Or you can simply add a middleware to convert `include` to `filter[include]`. It works perfect.
