### ISSUE TITLE
Is it possible to pass data from a custom endpoint to some method to make it change into JSON API format

### ISSUE THREAD

**Issue by devotox** [digitalsadhu/loopback-component-jsonapi#149]
I have a custom endpoint and would like to return the value in JSON API format. 

Just wondering if you have any way of doing this easily

**Comment by digitalsadhu** [comment]
Hey there,

Yes there are several ways. While you can do this with loopback-component-jsonapi directly it's a bit messy. I recently wrote a new module to improve this and will be integrating it into loopback-component-jsonapi when I get a chance. I would recommend you take a look.

https://www.npmjs.com/package/loopback-jsonapi-model-serializer

**Comment by devotox** [comment]
Ha this is exactly what i was looking for. Thank you once again

**Comment by digitalsadhu** [comment]
Glad to be of service :)
