### ISSUE TITLE
Model.disableRemoteMethod is deprecated

### ISSUE THREAD

**Issue by rigobcastro** [digitalsadhu/loopback-component-jsonapi#177]
I have this error:

```
Model.disableRemoteMethod is deprecated. Use Model.disableRemoteMethodByName instead. node_modules/loopback-component-jsonapi/lib/removeRemoteMethods.js:12:23
```

**Comment by digitalsadhu** [comment]
Ah yea, makes sense. I know where that will be happening, thanks for reporting.
This will be because of a change from loopback 2 to 3.

https://github.com/digitalsadhu/loopback-component-jsonapi/blob/master/lib/removeRemoteMethods.js#L12

Don't suppose you'd have time to submit a fix?
