### ISSUE TITLE
UPDATE doesn't build proper SQL string

### ISSUE THREAD

**Issue by csprocket777** [digitalsadhu/loopback-component-jsonapi#208]
This is my first loopback JSONAPI application, I'm using the latest Ember as my front end.

I'm trying to send an update to the server and am getting errors showing an invalid SQL string.

After inspecting the server side, here's the string it's trying to execute:
```
"UPDATE `member` SET  WHERE `id`=?"
```

Here's the request I'm sending to the server as a POST:
```
{
    "data":{
        "id":"1",
        "attributes":{
                "firstName":"[valid first name]",
                "lastName":"[valid last name",
                "email":"[valid email]",
                "username":"[valid email]"
        },
        "relationships":{
            "organization":{
                "data":{
                    "type":"organizations",
                    "id":"1"
                    }
                }
        },
        "type":"members"
    }
}
```

I followed the installation instructions (I believe). Any pointers would help. Thank you!

**Comment by digitalsadhu** [comment]
Hi @csprocket777 

Nothing screaming out at me from what you have posted so far.

Can you share your member and organization model definitions. Are they all correct? If you turn off loopback-component-jsonapi do things work as expected?

**Comment by JonathanPrince** [comment]
Hey @csprocket777, you mention that you are sending the example data with the POST method. Is that just a typo? Updating records in JSON API should be PATCH. Not sure if this even relevant or not, just wanted to clarify incase there's something else going on.

**Comment by csprocket777** [comment]
@JonathanPrince You're right, was a typo on my part. It is sending it over as a PATCH.

This is a shot of the network inspector of the PATCH from the client:
<img width="572" alt="screen shot 2017-04-10 at 1 29 08 pm" src="https://cloud.githubusercontent.com/assets/4195745/24876570/cdbcbe82-1df1-11e7-9b89-7078b7bf53af.png">

Here are my model files:
**member.js**
```
'use strict';

module.exports = function(Member) {
};
```

**member.json**
```
{
  "name": "member",
  "plural": "members",
  "base": "User",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "mixins": {
    "ClearBaseAcls": true
  },
  "properties": {
    "firstName": {
      "type": "string",
      "required": false
    },
    "lastName": {
      "type": "string",
      "required": false
    },
    "email": {
      "type": "string",
      "required": false
    },
    "phone": {
      "type": "string",
      "required": false
    },
    "password": {
      "type": "string",
      "required": false
    },
    "created_at": {
      "type": "date"
    },
    "updated_at": {
      "type": "date"
    },
    "is_account_rep": {
      "type": "Boolean",
      "required": false
    },
    "account_rep": {
      "type": "number",
      "required": false
    }
  },
  "validations": [],
  "relations": {
    "organization": {
      "type": "belongsTo",
      "model": "organization",
      "foreignKey": "organization"
    }
  },
  "acls": [
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "Administrator",
      "permission": "ALLOW"
    }
  ],
  "methods": {}
}
```

**organization.js**
```
'use strict';

module.exports = function(Organization) {

};
```

**organization.json**
```
{
  "name": "organization",
  "plural": "organizations",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "string",
      "required": true
    },
    "is_system_owner": {
      "type": "boolean",
      "required": true,
      "default": false
    },
    "created_at": {
      "type": "date",
      "required": true
    },
    "updated_at": {
      "type": "date",
      "required": true
    }
  },
  "validations": [],
  "relations": {
    "members": {
      "type": "hasMany",
      "model": "member",
      "foreignKey": "organization"
    }
  },
  "acls": [
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "Administrator",
      "permission": "ALLOW"
    }
  ],
  "methods": {}
}
```

**Comment by csprocket777** [comment]
Here's the details of the server response:
<img width="1280" alt="screen shot 2017-04-10 at 1 33 54 pm" src="https://cloud.githubusercontent.com/assets/4195745/24876732/6649c578-1df2-11e7-8ca6-b85e372b7dc9.png">

**Comment by hamzahio** [comment]
@digitalsadhu
same problme here i use mongodb and i PATCH endpoint receive only property if i give it payload like this 

```
{
  data:{
    id: "58f143c3a38f052286635651", 
    attributes: {
      name: "Burgarexwqeqr", 
      price: 22}, 
      type: "products"
  },
  attributes:{
    name: "Burgarexwqeqr", 
    price: 22
  },
  id:"58f143c3a38f052286635651",
  type:"products"
}

```

it take data key and create another property on the model called data and put everything in the request in it.

```
{
	"_id": ObjectId('58f143c3a38f052286635651'),
	"name": "Burgare",
	"price": 22,
	"data": {
		"id": "58f143c3a38f052286635651",
		"attributes": {
			"name": "Burgarexwqeqr",
			"price": 22
		},
		"type": "products"
	}
}

```

**Comment by hamzahio** [comment]
I pinpoint the problem is in this line deserialize.js#L52

https://github.com/digitalsadhu/loopback-component-jsonapi/blob/master/lib/deserialize.js#L52

the req didn't meet the IF requirements so it goes to else and didn't deserialize it. 

can you help me fix it because I need it in my project.

**Comment by hamzahio** [comment]
The req didn't have include!

```
function shouldApplyJsonApi (ctx, options) {
  if (!options.include) return false

  var modelName = ctx.method.sharedClass.name
  var methodName = ctx.method.name
  var model
  var methods
  for (var i = 0; i < options.include.length; i++) {
    model = options.include[i].model
    methods = options.include[i].methods
    if (model === modelName && !methods) return true
    if (!model && methods === methodName) return true
    if (model === modelName && methods === methodName) return true
    if (model === modelName && _.includes(methods, methodName)) return true
  }
  return false
}

```

**Comment by hamzahio** [comment]
@JonathanPrince Your help is need thanks. 👍

**Comment by hamzahio** [comment]
Sorry for the trouble I found the error is you look for **updateAttributes** and it is **patchAttributes**

**Comment by csprocket777** [comment]
Thank you, with #213 and #210, this issue is resolved!
