### ISSUE TITLE
Improve error handling code

### ISSUE THREAD

**Issue by digitalsadhu** [digitalsadhu/loopback-component-jsonapi#22]
I have submitted a PR to strong-remoting to allow us to handle all errors in a single error handler. This should allow us to clean up the code dramatically.

See: https://github.com/strongloop/strong-remoting/pull/248

Once the PR is accepted, we need to use: 
```js
app.remotes().options.rest.handleErrors = false;
```
To disable the RestAdapter errorhandler and we can rely on our error handler middleware to catch all errors from then on.

We can also drop afterError handling as its not needed

Checklist:
- [x] remove duplicated error handling
- [x] generalise error codes for validation errors eg. 400 with array of validation errors with 422 status code.
- [x] clean up code
- [x] create separate errors test file, expand errors testing
- [x] expand tests

**Comment by digitalsadhu** [comment]
PR accepted!,
This can be done

**Comment by digitalsadhu** [comment]
Ok, working on this now/today.

Checklist:
[ ] - remove duplicated error handling
[ ] - generalise error codes for validation errors eg. 400 with array of validation errors with 422 status code.
[ ] - clean up code
[ ] - create separate errors test file, expand errors testing

**Comment by listepo** [comment]
:+1:
