### ISSUE TITLE
reflexive relationship

### ISSUE THREAD

**Issue by BenjaminHorn** [digitalsadhu/loopback-component-jsonapi#238]
**database folder table**

id | name | parentId
------------ | ------------- | ----------
1 | Folder 1 | 0
2 | Folder 2 | 1
3 | Folder 3 | 1
4 | Folder 4 | 3

**models/folder.json**

```Javascript
  "relations": {
    "parent": {
      "type": "belongsTo",
      "model": "Folder",
      "foreignKey": "parentId"
    },
    "children": {
      "type": "hasMany",
      "model": "Folder",
      "foreignKey": "parentId"
    }
  }
```
**GET /folders/1/children**
```JSON
{
  "links": {
    "self": "http://127.0.0.1:35626/folders/1/children"
  },
  "data": [
    {
      "type": "folders",
      "relationships": {
        "children": {
          "links": {
            "related": "http://127.0.0.1:35626/folders/2/children"
          }, // do we need data key?
          "data": {
            "type": "folders",
            "id": 1
          }
        },
        "parent": {
          "links": {
            "related": "http://127.0.0.1:35626/folders/2/parent"
          }, // do we need data key?
          "data": {
            "type": "folders",
            "id": 1
          }
        }
      },
      "id": "2",
      "attributes": {
        "name": "Folder 2"
      },
      "links": {
        "self": "http://127.0.0.1:35626/folders/2"
      }
    },
    {
      "type": "folders",
      "relationships": {
        "children": {
          "links": {
            "related": "http://127.0.0.1:35626/folders/3/children"
          }, // do we need data key?
          "data": {
            "type": "folders",
            "id": 1
          }
        },
        "parent": {
          "links": {
            "related": "http://127.0.0.1:35626/folders/3/parent"
          }, // do we need data key?
          "data": {
            "type": "folders",
            "id": 1
          }
        }
      },
      "id": "3",
      "attributes": {
        "name": "Folder 3"
      },
      "links": {
        "self": "http://127.0.0.1:35626/folders/3"
      }
    }
  ]
}
```

~~I would expect that the first child of _Folder 1_ (_Folder 2_) has no children, and the second child (_Folder 3_) has one child (_Folder 4_) in an array, since `children` is a hasMany relation.~~

_Edit_: Looking through the hasMany tests, it looks like in this case `data` key in relationships should not be present at all. This test https://github.com/digitalsadhu/loopback-component-jsonapi/blob/master/test/hasMany.test.js#L155-L170  produces the following result:

```JSON
[
  {
    "type": "comments",
    "relationships": {
      "replies": {
        "links": {
          "related": "http://127.0.0.1:36476//comments/1/replies"
        }
      }
    },
    "id": "1",
    "attributes": {
      "title": "My comment",
      "comment": "My comment text"
    },
    "links": {
      "self": "http://127.0.0.1:36476//comments/1"
    }
  },
  {
    "type": "comments",
    "relationships": {
      "replies": {
        "links": {
          "related": "http://127.0.0.1:36476//comments/2/replies"
        }
      }
    },
    "id": "2",
    "attributes": {
      "title": "My second comment",
      "comment": "My second comment text"
    },
    "links": {
      "self": "http://127.0.0.1:36476//comments/2"
    }
  }
]
```
In relationship there is only `link` key. Is this the expected result?

We try to serve an ember.js client with a simular setup: https://guides.emberjs.com/v2.14.0/models/relationships/#toc_reflexive-relations

I added a failing test: https://github.com/digitalsadhu/loopback-component-jsonapi/blob/reflexive-relationship/test/reflexiveRelationship.test.js

**Comment by digitalsadhu** [comment]
Yea so the general approach is that if we side load data then we should include the relationships data block so that the included data can be linked to. Otherwise we should not include the data block so that clients can use the relationships related link to fetch the data as needed. It is fine to include the data block as far as the spec is concerned l, however in the case of Ember, the data block will be used to fetch each related resource one at a time and won't use the related link which in the case on hasMany is much more efficient. So basically, best not to include the data block unless we are side loading.
