### ISSUE TITLE
Update semantic-release and add additional tooling

### ISSUE THREAD

**Issue by digitalsadhu** [digitalsadhu/loopback-component-jsonapi#267]
Semantic release has changed its api. We will need to update things a little in order to support it. We can follow migration instructions [here](https://github.com/semantic-release/semantic-release/releases)

While we are at it, we should add [commitizen](https://github.com/commitizen) and [commitlint](https://github.com/marionebl/commitlint) to ensure commit messages are correctly formed.

**Comment by Tronix117** [comment]
Il semblerait que `sementic-release` ait besoin d'une version dans le `package.json` désormais, il me semble qu'avant, il l'ajoutait automatiquement avant le publish...

**Comment by Tronix117** [comment]
Fix with #268 and #40f9282
