### ISSUE TITLE
Example using options.meta?

### ISSUE THREAD

**Issue by sacarino** [digitalsadhu/loopback-component-jsonapi#288]
Hi there.

I saw in this (merged) [PR 116](https://github.com/digitalsadhu/loopback-component-jsonapi/pull/116) that the ability to add content into the meta tag was [added](https://github.com/JonForest/loopback-component-jsonapi/blob/c9b4ded39735ee7bdf102932e9cb67a150a7a642/lib/serializer.js#L24).

@JonForest or @digitalsadhu would it be possible to get some example of how to use it? I was hoping `meta` would work out of the box on the `GET` routes so pagination would be cake but that doesn't seem to be the case.

**Comment by JonForest** [comment]
We tend to add items onto the meta in the `afterRemote` methods.  E.g. something like this:
(note: this is a bit hacked about, but you'll get the idea)
```
ModelName.afterRemote('find', (ctx, instance, cb) => {
    if (!ctx.res.headersSent && limit) {
        // ctx.method.ctor -> constructor, the static object that was used in the find
        ctx.method.ctor.count(ctx.args.filter.where, (err, count) => {
          ctx.meta = { 'total_pages': Math.ceil(count / ctx.args.filter.limit) }
          cb(err)
        })
      } else {
        cb()
      }
})
```

**Comment by sacarino** [comment]
Ah, this is brilliant. I made a mixin for this, works great. Appreciate the pointer!
