### ISSUE TITLE
Publishing releases

### ISSUE THREAD

**Issue by digitalsadhu** [digitalsadhu/loopback-component-jsonapi#36]
@listepo @tsteuwer 
I wanted to get some feedback on how we publish releases:

Currently, I'm not entirely following semver as the project still has a lot of work to do before I think its ready for a 1.0 release. I think that until 1.0 we should treat the minor number as major and the patch number as minor and patch. Once we hit 1.0, we can start following semver properly.

**Eg.**
**Before 1.0.0**
- Breaking change, current version 0.4.0 goes to 0.5.0
- Feature addition, current version 0.4.0 goes to 0.5.1
- Bug fixes, current version 0.4.0 goes to 0.5.1

**After 1.0.0**
- Breaking change, current version 1.0.0 goes to 2.0.0
- Feature addition, current version 1.0.0 goes to 1.1.0
- Bug fixes, current version 1.0.0 goes to 1.0.1

**Comment by tsteuwer** [comment]
This sounds like a good plan to me. Let's start the full semver at 1

**Comment by digitalsadhu** [comment]
:+1:

**Comment by digitalsadhu** [comment]
Decision made, closing issue.
