### ISSUE TITLE
What happens if a user defines a hasOne to a model named relationships?

### ISSUE THREAD

**Issue by digitalsadhu** [digitalsadhu/loopback-component-jsonapi#44]
GET /:model/:id/relationships
GET /:model/:id/relationships/relationships

:boom:

**Comment by tsteuwer** [comment]
We may need to go to json api spec guys for this. I'll post a question on their forums

**Comment by tsteuwer** [comment]
@digitalsadhu see comments posted [here](https://github.com/json-api/json-api/issues/912)

**Comment by digitalsadhu** [comment]
Nice one @tsteuwer!
Thanks for taking the time to follow up on that one!

**Comment by tsteuwer** [comment]
Is this good to close?

**Comment by digitalsadhu** [comment]
Was going to ask you the same. Go right ahead!
