### ISSUE TITLE
null relationship data

### ISSUE THREAD

**Issue by BenjaminHorn** [digitalsadhu/loopback-component-jsonapi#47]
### in my database

**service** table

id | name| service-group-id
------------ | -------------|----------
1 | service1|1
**service-group** table

id | name| 
------------ | -------------
1 | service-group1

### Loopback
**service.json**

```javascript
{
  "name": "service",
...
  "include": ["service-group"],
  "properties": {
    "name": {
      "type": "string",
      "required": true
    },
    "service-group-id": {
      "type": "number"
    }
  },
  "relations": {
    "service-group": {
      "type": "belongsTo",
      "model": "service-group",
      "foreignKey": "service-group-id"
    }
  },
...
}
```
### localhost:3000/explorer
**http://localhost:3000/api/services**
```javascript
{
  "data": [
    {
      "type": "services",
      "relationships": {
        "service-group": {
          "data": null
        }
      },
      "id": "1",
      "attributes": {
        "name": "service1"
      },
      "links": {
        "self": "http://localhost:3000/api/services/1"
      }
    }
  ]
}

```

**http://localhost:3000/api/services/1/service-group**

```javascript
{
  "data": {
    "type": "service-groups",
    "id": "1",
    "attributes": {
      "name": "service-group1"
    },
    "links": {
      "self": "http://localhost:3000/api/service-groups/1"
    }
  },
  "links": {
    "self": "http://localhost:3000/api/services/1/service-group"
  }
}
```

Why is service-group.data: null? Should not included some data like this suggests: http://emberjs.com/api/data/classes/DS.JSONAPISerializer.html?

**Comment by digitalsadhu** [comment]
Thanks for the great write up here. 

I think there are a couple things going on here. 

1. You aren't using the include syntax in the url so the related Sarai's not fetched/available by default. 

2. When you don't include the include filter in the url, what I think you should see is a links object with a related link to the related data. You aren't seeing that which is a bug on our part. 

Can you try using the include filter in the url and report back what you see?

**Comment by BenjaminHorn** [comment]
what is the right syntax for include filter? 
http://localhost:3000/api/services?filter={"include": "service-group"} produces:

*{"error":{"name":"Error","status":500,"message":"Relation \"service-group\" is not defined for service-group model","stack":"Error: Relation \"service-group\" is not defined for service-group ...*

P.S.:

**models/service.js**
```javascript
import DS from 'ember-data';

export default DS.Model.extend({
  name: DS.attr('string'),
  category: DS.belongsTo('service-group')
});
```
How can I send the right request (with filter include) in Ember?
```javascript
import Ember from 'ember';

export default Ember.Route.extend({
  model: function() {
    return this.store.findAll('service');
  }
});
```

**Comment by digitalsadhu** [comment]
Just to follow up a bit. This is what I would expect to see:

## Without includes filter:

Just the links to the related data should be included. Something like the following:

GET http://localhost:3000/api/services

```js
{  
   "data":[  
      {  
         "type":"services",
         "relationships":{  
            "category":{  
               "links": {
                 "self": "http://localhost:3000/api/services/1/relationships/category",
                 "related": "http://localhost:3000/api/services/1/category"
               }
            }
         },
         "id":"1",
         "attributes":{  
            "name":"service1"
         },
         "links":{  
            "self":"http://localhost:3000/api/services/1"
         }
      }
   ],
   "links":{  
      "self":"http://localhost:3000/api/services"
   }
}
```
Example here: http://api.pixelhandler.com/api/v1/posts

## With the include filter

I would expect to see the relationship data and also a root level `included` key. Something like the following:

GET http://localhost:3000/api/services?filter={"include":"service-group"}
or
GET http://localhost:3000/api/services?filter[include]=service-group

```js
{  
   "data":[  
      {  
         "type":"services",
         "relationships":{  
            "category":{  
               "links": {
                 "self": "http://localhost:3000/api/services/1/relationships/category",
                 "related": "http://localhost:3000/api/services/1/category"
               },
               "data": {"type": "category", "id": 1}
            }
         },
         "id":"1",
         "attributes":{  
            "name":"service1"
         },
         "links":{  
            "self":"http://localhost:3000/api/services/1"
         }
      }
   ],
   "links":{  
      "self":"http://localhost:3000/api/services?filter[include]=service-group"
   },
   "included": [
     {
       "type": "category", 
       "id": 1,
       "links": {
         "self": "..."
       },
       "attributes": {
         ...
       }
     }
   ]
}
```

See here for an example:
http://api.pixelhandler.com/api/v1/comments?include=post

**Comment by digitalsadhu** [comment]
And in ember you would then do something like:

```js
import Ember from 'ember';

export default Ember.Route.extend({
  model: function() {
    return this.store.findAll('service', {
      filter: {
        include: 'service-group'
      }
    });
  }
});
```

Note: completely untested!

**Comment by tsteuwer** [comment]
I'll add tests for this in the [emberloop](https://github.com/tsteuwer/emberloop) project

**Comment by tsteuwer** [comment]
FYI to all: According to the JSON API spec:

[Fetching Includes](http://jsonapi.org/format/#fetching-includes)
> An endpoint MAY also support an include request parameter to allow the client to customize which related resources should be returned.
> [...]
>> GET /articles/1?include=comments HTTP/1.1
>> Accept: application/vnd.api+json

The way you'd do this in Ember (with Ember Data), would be to use queryRecord like so:
```
this.store.queryRecord('person', {
    include: 'address',
    filter: {
       name: 'blah'
    }
});
```

This would then be translated to:

```
GET /person?include=address&filter[name]=blah
```

**Comment by tsteuwer** [comment]
Tests have been added in emberloop. They are currently failing. @digitalsadhu  i need to add you as a contrib. i'll add you now.

**Comment by digitalsadhu** [comment]
Nice one @tsteuwer!
Include in loopback has a different syntax although it should work essentially the same so the best way to handle it is probably to find a way to map jsonapi syntax to loopback.

**Comment by BenjaminHorn** [comment]
I'm running only the **belongsTo.test.js** and in my console.log https://github.com/digitalsadhu/loopback-component-jsonapi/blob/master/lib/serialize.js#L85 looks like this:

```javascript
{ data: 
   { type: 'comments',
     id: '1',
     attributes: { 'post-id': 1, title: 'my comment', comment: 'my post comment' },
     links: { self: 'http://127.0.0.1:33275/api/comments/1' } },
  links: { self: 'http://127.0.0.1:33275/comments/1' } }
```
As you can see "relationships" are missing, which is not a surprise because https://github.com/digitalsadhu/loopback-component-jsonapi/blob/master/lib/utils.js#L32 is always undefined, (should this work?) 
What I dont get: in my application the response from server has the relationship object see https://github.com/digitalsadhu/loopback-component-jsonapi/blob/master/lib/utils.js#L32. Links are missing, but it is there.

**Comment by digitalsadhu** [comment]
@BenjaminHorn Both links above are the same. Is that what you intended?

**Comment by digitalsadhu** [comment]
Relationships support is very patchy at this point. We have a lot of tests written but now we need to make them pass. 

On that note, @BenjaminHorn if you have any capacity to help out at all, do let me know. Theres a few issues now that have all the tests written and are well specced out. (See help wanted issues in the issue tracker). Some bigger than others. Sing out if you want any clarification.

**Comment by BenjaminHorn** [comment]
@digitalsadhu no, the 2nd link should point to one of my comments. It shows the response from the server. It has relationships object, but in the tests comments do not have it.

**Comment by digitalsadhu** [comment]
I have uncommented a bunch of tests related to relationships showing correctly in the case where the `include` filter is not used. There are now 14 failing tests. I think this is a good place to start. It will be easier to get this fixed quickly. See 61753855fbd551e05bda96ad74ed22a4d81dd751
