### ISSUE TITLE
Code Cleanup

### ISSUE THREAD

**Issue by tsteuwer** [digitalsadhu/loopback-component-jsonapi#50]
I'm trying to get my hands wet on the back-end side so I can start helping with some of these issues. Some of the code is messy and can easily be cleaned up. Would anybody mind if I took this chance to clean up the code and learn a bit about how things work in this?

**Comment by digitalsadhu** [comment]
Sounds good to me.

**Comment by tsteuwer** [comment]
@digitalsadhu , mind doing the code review for https://github.com/digitalsadhu/loopback-component-jsonapi/pull/52 and merge if you're good with it?

**Comment by digitalsadhu** [comment]
You bet! Will look at this today!
