### ISSUE TITLE
loopback's filter param doesn't work with the component.

### ISSUE THREAD

**Issue by tsteuwer** [digitalsadhu/loopback-component-jsonapi#62]
If you open up the emberloop project and go to 127.0.0.1:4200 and watch it run through the tests, the filter test fails with:

```
GET /person?filter[firstName]=John (returned 4 instead of returning 1)
```

The test only creates 1 ``person`` object with the firstName of John.

**Comment by digitalsadhu** [comment]
@tsteuwer What do you make of this? Is it somehow possible multiple test runs aren't getting cleaned up or something?

**Comment by tsteuwer** [comment]
@digitalsadhu, somehow the Loopback functionality is lost. If you go to the response where it returns the data from this query, it's returning every ``person`` object, not just the filtered one (they all have different ``firstName``'s btw, eg. sue, john, joe).

**Comment by tsteuwer** [comment]
I'm going to make a test with this and i'll push it up for you to checkout.

**Comment by digitalsadhu** [comment]
I think the problem could be incorrect filter syntax:
Rather than:
```
GET /person?filter[firstName]=John
```
It's probably:
```
GET /person?filter[where][firstName]=John
```

See filter documentation for loopback:
Where filter: https://docs.strongloop.com/display/public/LB/Where+filter
Fields filter: https://docs.strongloop.com/display/public/LB/Fields+filter

**Comment by digitalsadhu** [comment]
Closing, tests added in #64
